name: Generate Presenter Profile
description: Generate a comprehensive presenter profile by automatically searching CNCF YouTube
title: ""
labels: ["type/presenter-profile"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Generate a comprehensive presenter profile by automatically searching the CNCF YouTube channel.
        
        **What happens:**
        - Searches CNCF channel for presenter's talks (past 2 years)
        - Fetches all matching videos automatically
        - Analyzes expertise, CNCF projects, and recurring themes
        - Generates profile with biography and statistics
        
        **Output:** Markdown profile with biography, expertise areas, talk highlights, and fun statistics.
        
        **Target audience:** CNCF community, contributor recognition
        
        **Requirements:**
        - Presenter has given at least 1 substantive talk (10+ minutes) at CNCF events
        - Presenter name appears in video titles or descriptions
        - Videos have captions/subtitles enabled
        - Short videos (announcements, closings) are automatically filtered out

  - type: input
    id: presenter_name
    attributes:
      label: Presenter Name
      description: Full name of the presenter as it appears in video titles
      placeholder: e.g., Jeffrey Sica, Kelsey Hightower
    validations:
      required: true

  - type: input
    id: github_username
    attributes:
      label: GitHub Username (Optional but Recommended)
      description: Provides better biographical data, profile linking, and name disambiguation
      placeholder: e.g., jeefy, kelseyhightower

  - type: textarea
    id: cncf_projects
    attributes:
      label: Expected CNCF Projects (Optional)
      description: CNCF projects discussed in the videos (helps validate search results)
      placeholder: |
        - Kubernetes
        - Prometheus
        - Envoy

  - type: markdown
    attributes:
      value: |
        ## Processing Pipeline
        
        The people-agent will execute a 16-step workflow with automatic video discovery:
        
        **New Profile Path:**
        1. Search CNCF YouTube channel for presenter (past 2 years)
        2. Fetch GitHub profile data
        3. Fetch all matching videos and validate
        4. Extract biography and validate presenter name
        5. Analyze all talks for expertise, CNCF projects, and themes
        6. Generate profile content
        7. Validate profile quality (≥0.60 score required)
        8. Assemble markdown with fun statistics
        9. Create pull request
        
        **Update Profile Path (if profile exists):**
        1. Load existing profile
        2. Search for new videos
        3. Validate profile update safety
        4. Re-aggregate all talks
        5. Update profile content
        6. Create pull request with change summary
        
        **Processing time:** Approximately 15 minutes for new profiles
        
        **Output location:** `people/github-username.md` with JSON metadata
        
        ## Validation Checkpoints
        
        The workflow includes 6 critical validation checkpoints:
        - Video search results (minimum 1 video over 10 minutes required)
        - Multi-video data quality (transcripts ≥1000 chars)
        - Presenter name verification (found in ≥50% of videos)
        - Biography quality (minimum 100 chars, no placeholders)
        - Talk aggregation (≥1 CNCF project, valid summaries)
        - Overall quality score (≥0.60 required, ≥0.70 target)
        
        ## Critical Failure Scenarios
        
        The workflow will stop and post an error if:
        - No videos found in CNCF channel for presenter
        - All video fetches fail or transcripts empty
        - Presenter name not found or conflicting names detected
        - Biography contains placeholders or fabricated information
        - No CNCF projects identified in any talk
        - Quality score below 0.60
        - Profile update conflict (different presenter in new videos)
